added the has_many and belongs_to to the models.
CdLeng/concertify pull request #8
Opened 2023-03-06 19:57 UTC by isaquito1993

Please double check this as im not too sure

2023-03-06 20:31 UTC, carolinavmo requested changes

2023-03-06 20:31 UTC, carolinavmo commented on app/models/artist.rb
> +  has_many :followed_concerts
has_many :followed_**artists** ?

2023-03-06 21:19 UTC, isaquito1993 commented on app/models/artist.rb
> +  has_many :followed_concerts
lol. yes 😅

2023-03-06 21:23 UTC, isaquito1993 commented on app/models/artist.rb
> +  has_many :followed_concerts
have changed it

2023-03-07 15:28 UTC, CdLeng commented on app/models/artist.rb
> +  has_many :artist_genres
I think it's `has_many :genres through :artist_genres`, because the artist_genres table is a JOIN table @isaquito1993

2023-03-07 15:59 UTC, CdLeng commented on app/models/artist.rb
> +  has_many :followed_artists
`has_many :artist_genres`

2023-03-07 16:23 UTC, merged